apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudzero-cloudwatch-metrics.fullname" . }}
  labels:
    {{- include "cloudzero-cloudwatch-metrics.labels" . | nindent 4 }}
data:
  cwagentconfig.json: |
{{- if .Values.agentConfig }}
{{ .Values.agentConfig }} | nident 2}}
{{ else }}
    {
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "{{ .Values.clusterName }}",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }
{{- end }}
