apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudzero-cloudwatch-metrics.fullname" . }}
  labels:
    {{- include "cloudzero-cloudwatch-metrics.labels" . | nindent 4 }}
data:
  cwagentconfig.json: |
    {{- if .Values.agentConfig }}
    {{- tpl .Values.agentConfig . | nindent 4 }}
    {{- else }}
    {
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "{{ .Values.clusterName }}",
            {{- $allowedIntervals := list 5 10 15 30 45 60 120 }}
            {{- $failureMessage := printf "metricsCollectionInterval must be set to one of %s" (join "," $allowedIntervals) }}
            {{- if not (has (int .Values.metricsCollectionInterval) $allowedIntervals) }}
              {{- fail $failureMessage }}
            {{- else }}
            "metrics_collection_interval": {{ .Values.metricsCollectionInterval }}
            {{- end }}
          }
        },
        "force_flush_interval": 5
      }
    }
    {{- end }}

