name: Branch Push validations
on:
  push:
    branches-ignore:
      - gh-pages
      - main
  workflow_dispatch:
jobs:
  verify-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install tool Chain
        run: ./scripts/install-toolchain.sh

      - name: get fetch to update tags locally
        run: git fetch --prune --unshallow --tags
        if: ${{ git rev-parse --is-shallow-repository }}

      - name: verify the release 
        run: make all
