name: Branch Push validations
on: [push, workflow_dispatch]
jobs:
  verify-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/install-toolchain.sh
      - run: git log --graph --decorate --pretty=oneline --abbrev-commit
      - run: make all
