name: Main Push Continuous Deployment
on:
  push:
    branches:
      - action-gh-pages
jobs:
  Deployment:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      PUBLISH_DIR: build/stable
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: get fetch to update tags locally
        run: git fetch --prune --unshallow --tags

      - name: last tag
        run: |
          LAST_TAG=$(git describe HEAD --tags | grep -Eo "^v[0-9]+(\.[0-9]+)*")
          echo "LAST_TAG=${LAST_TAG}"
          echo "LAST_TAG=${LAST_TAG}" >> $GITHUB_ENV

      - name: previous tag
        run: echo ${{ env.LAST_TAG }}

      - name: installing tool chain
        run: ./scripts/install-toolchain.sh

      - name: verify the release one more time.
        run: make all

      - name: Draft release
        run: ./scripts/draft-release.sh

      - name: Package release
        run: |
          ./scripts/package-charts.sh
          echo generate index
          helm repo index . --url https://cloudzero.github.io/cloudzero-k8s-charts/
          cp index.yaml ${{ env.PUBLISH_DIR }} 

      - name: list
        run: |
         find build -print

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
          exclude_assets: '.nojekyll,LICENSE,README.md,index.yaml,*.tgz'

      - name: list
        run: |
         find build -print


